version: '3'
services:
    satisfactory-server:
        build: .
        image: 'sunmachine/satisfactory-server:latest'
        container_name: 'satisfactory-server-container'
        hostname: 'satisfactory-server'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/sunmachine/satisfactory/config:/config'
        environment:
            - MAXPLAYERS=8
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: unless-stopped